apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ghislaingenay/redifood-client
          env:
            - name: NEXT_PUBLIC_CLOUDINARY_NAME
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_CLOUDINARY_NAME
                  name: secret
            - name: NEXT_PUBLIC_UPLOAD_PRESET
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_UPLOAD_PRESET
                  name: secret

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clientSrv }}
  namespace: default
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: { { .Values.clientPort } }
      targetPort: { { .Values.clientPort } }
