apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: {{ .Values.hostSecret }}-tls
spec:
  secretName: { { .Values.hostSecret } }
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: { { .Values.prodDomain } }
  dnsNames:
    - { { .Values.prodDomain } }
    -  { { .Values.prodWwwDomain } }
  # https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11628364#questions/8558842/
