import { Typography } from "antd";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography.Title level={5}>Hello</Typography.Title>
        <h1 className="text-2xl font-bold underline">Hello world!</h1>
      </main>
    </div>
  );
}
