apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: food-redicoding-com-tls
spec:
  secretName: food-redicoding-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: redifood.redicoding.com
  dnsNames:
    - redifood.redicoding.com
    - www.redifood.redicoding.com
  # https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11628364#questions/8558842/
