apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: rediapp-net-tls
spec:
  secretName: rediapp-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rediapp.net
  dnsNames:
    - rediapp.net
    - www.rediapp.net
  # https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11628364#questions/8558842/
