export * from "./auth.interface";
export * from "./class.interface";
export * from "./food.interface";
export * from "./global.interface";
export * from "./nav.interface";
export * from "./order.interface";
export * from "./settings.interface";
export * from "./test.interface";
export * from "./payment.interface";
