name: backend
on:
  pull_request:
    branches:
      - master
      -  RED-16-monolith-app
    paths:
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: cd backend && npm run build
