name: backend
on:
  pull_request:
    branches:
      - master
      - development-monolith
    paths:
      - "backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install depedencies
        run: cd backend && npm install & npm i @nestjs/cli       
      - name: Build 
        run: npm run build
