name: backend
on:
  pull_request:
    branches:
      - master
      - development-monolith
    paths:
      - "backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install depedencies
        run: cd backend && npm install & npm i @nestjs/cli
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Verify npm classic 1
        run: cd backend && npm run
      - name: Build
        run: cd backend && npm run-script build
