name: client
on:
  pull_request:
    branches:
      - master
      - development-monolith
    paths:
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: cd client && npm install --omit=dev && npm run build
