name: client
on:
  pull_request:
    paths:
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: cd client && npm ci --ignore-scripts && npm run test:ci
