name: client
on:
  pull_request:
    paths:
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client && npm ci --ignore-scripts && npm run test:ci
