name: deploy-client
on:
  push:
    branches:
      - master
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Sign In Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: cd client && docker build -t ghislaingenay/redifood-client .
      - name: Push image to Docker Hub
        run: docker push ghislaingenay/redifood-client
      - name: Activate Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save Cluster
        run: doctl kubernetes cluster kubeconfig save redifood
      - name: Restart Client container
        run: kubectl rollout restart deployment client-depl
