name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Activate Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save Cluster
        run: doctl kubernetes cluster kubeconfig save redifood
      - name: Apply Kubernetes config files
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
