name: foods
on:
  pull_request:
    paths:
      - 'foods/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: cd foods && npm install && npm run test:ci
